### ISSUE TITLE
wb command error on Windows 

### ISSUE THREAD

**Issue by akkashyap** [Washington-University/workbench#15]
I keep getting a  ' ERROR: Parse error while reading: Tried to read 365128 from ' when I try to execute the wb command  [wbcommand ' -cifti-convert -from-gifti-ext ' filename '.gii ' filename]. I had no problems when I was trying to use the same wb command in mac. 

In general I am having trouble to save a dtseries cifti file. (I tried ft_read_cifti + ft_write_cifti but I ran into issues with the transform matrix which kept distorting my values into a random space)

Any thoughts? Ideas?

**Comment by coalsont** [comment]
That error should happen when the gifti file is corrupted, due to the external binary file being the wrong size - try using the same wb_command on the same gifti file on mac, you should get the same error.

I suspect either you have two different versions of the gifti toolbox installed on mac vs windows (and one is doing something wrong), or windows is having problems writing to a network share, or permissions problems, or something like that.

**Comment by akkashyap** [comment]
Thanks, 
Yeah I can't get the error on Mac. I transferred the intermediate gifti file created from my Mac and windows still can't run the command. I think its a windows permission problem (although running as an administrator doesn't seem to fix it). I have had a few of those issues on windows 10.

**Comment by coalsont** [comment]
Note that there are two files that must be transferred for the command to work: the .gii file, and a second larger binary file, that should have a similar name.

The error in your first comment should mean that it opened the binary file for reading, but it was smaller than it should have been.  Make sure you are still getting the same error, and not slightly different error text.

However, I have identified a possible issue with text vs binary file reading mode on the external binary file.  Since OS X uses just LF, same as C/C++ text IO and linux, it would be only windows that exposes text mode IO issues.  Try the windows64 dev_latest zip file here:

http://brainvis.wustl.edu/workbench/

**Comment by akkashyap** [comment]
Cool, yeah I will try it out. How do you compile all the html files into wb_command? (Sorry for the noob ?)

**Comment by coalsont** [comment]
The html files are a secondary output, created by running wb_command a bunch of times with a shell script, they aren't what you want.

There are several "dev_latest" zip files in that link, choose the one with "windows64" in the name.

**Comment by glasserm** [comment]
If you aren't doing MEG stuff, we don't recommend using the ft CIFTI options at this time, as they aren't compatible with the MRI data.  Instead, use the commands in 2B here: https://wiki.humanconnectome.org/display/PublicData/HCP+Users+FAQ

**Comment by akkashyap** [comment]
COALSONT you are amazing!!! you fixed the issue on windows thanks a bunch. 

glasserm, yeah I have trouble with the ft command to get them working. I thought this route (ciftiopen + ciftisave) is a bit more reliable since I can save the same file I opened (which ft has a problem with).

**Comment by coalsont** [comment]
As for the ft_read_cifti, etc functions, you might take a look at the open issues on https://github.com/robertoostenveld/cifti-matlab , and if the problem you had isn't related to them, open an issue there.
