### ISSUE TITLE
Build fails due to GLAPI being undefined

### ISSUE THREAD

**Issue by kloewe** [Washington-University/workbench#26]
Upon trying to build workbench on Ubuntu 17.10, I get the following errors.
```
In file included from /home/loewe/workspace/external/workbench/src/Operations/OperationShowScene.cxx:30:0:
/usr/include/GL/osmesa.h:122:1: error: 'GLAPI' does not name a type; did you mean 'GLEWAPI'?                                                                             
 GLAPI OSMesaContext GLAPIENTRY                                                                                                                                          
 ^~~~~
...
```
Here are my build commands (log files: [cmake.log](https://github.com/Washington-University/workbench/files/1471687/cmake.log), [make.log](https://github.com/Washington-University/workbench/files/1471688/make.log)).
```
$ cmake -D CMAKE_BUILD_TYPE=Release -D WORKBENCH_MESA_DIR=/usr -D WORKBENCH_USE_QT5=TRUE -Wno-dev ../src > cmake.log 2>&1
$ make -j16 > make.log 2>&1
```
The problem seems to result from the following situation.
- `OperationShowScene.cxx` first includes `glew.h` and then includes `osmesa.h`
- `glew.h` defines `__gl_h_` so that `gl.h` will not be included again
- `glew.h` defines `GLAPI` but undefines it in the end
- `osmesa.h` would include `gl.h` but doesn't because `__gl_h_` has already been defined by `glew.h`
- `GLAPI` remains undefined resulting in the observed errors

A workaround that enables me to build is to define `GLAPI` in `OperationShowScene.cxx` in case it's not defined.
```
#ifdef HAVE_OSMESA
#ifndef GLAPI
#define GLAPI extern
#endif
#include <GL/osmesa.h>
#endif // HAVE_OSMESA
```
Is this an acceptable solution?

**Comment by johnvelab** [comment]
At this time, we only use GLEW on Windows.  Our Linux systems do not have GLEW ("GLEW: No” appears in the “summary from running CMake”), otherwise we probably would have received this error.

I have pushed out an updated src/CMakeLists.txt (around line 281) so that find_package for GLEW is only executed on Windows.


#
# Look for GLEW but only on Windows
#
SET(GLEW_RESULT "No")
IF (WIN32)
    FIND_PACKAGE(GLEW)
ENDIF ()


I will admit that this does not fix the actual GLEW and Mesa conflict.  A web search shows others experiencing this problem but with no obvious solution.

John Harwell


On Nov 14, 2017, at 10:54 AM, Kristian Loewe <notifications@github.com<mailto:notifications@github.com>> wrote:


Upon trying to build workbench on Ubuntu 17.10, I get the following errors.

In file included from /home/loewe/workspace/external/workbench/src/Operations/OperationShowScene.cxx:30:0:
/usr/include/GL/osmesa.h:122:1: error: 'GLAPI' does not name a type; did you mean 'GLEWAPI'?
 GLAPI OSMesaContext GLAPIENTRY
 ^~~~~
...


Here are my build commands (log files: cmake.log<https://github.com/Washington-University/workbench/files/1471687/cmake.log>, make.log<https://github.com/Washington-University/workbench/files/1471688/make.log>).

$ cmake -D CMAKE_BUILD_TYPE=Release -D WORKBENCH_MESA_DIR=/usr -D WORKBENCH_USE_QT5=TRUE -Wno-dev ../src > cmake.log 2>&1
$ make -j16 > make.log 2>&1


The problem seems to result from the following situation.

  *   OperationShowScene.cxx first includes glew.h and then includes osmesa.h
  *   glew.h defines __gl_h_ so that gl.h will not be included again
  *   glew.h defines GLAPI but undefines it in the end
  *   osmesa.h would include gl.h but doesn't because __gl_h_ has already been defined by glew.h
  *   GLAPI remains undefined resulting in the observed errors

A workaround that enables me to build is to define GLAPI in OperationShowScene.cxx in case it's not defined.

#ifdef HAVE_OSMESA
#ifndef GLAPI
#define GLAPI extern
#endif
#include <GL/osmesa.h>
#endif // HAVE_OSMESA


Is this an acceptable solution?

**Comment by kloewe** [comment]
I wasn't aware that you don't use GLEW on Linux. Thanks!
