### ISSUE TITLE
GIfTI image orientation

### ISSUE THREAD

**Issue by neurolabusc** [Washington-University/workbench#28]
When I attempt to load reference[ GIfTI images](https://www.nitrc.org/frs/?group_id=75) they appear upside down (flipped in the head-foot dimension). Viewing the GIfTI header with a text editor suggests it uses an identity matrix, so this would not be influenced by applying the matrix to the points. I am using wb_view 1.3.2 on MacOS. The images that look wrong are the Brainvisa GIFTI samples v1.3 included in the BV_GIFTI_1.3.tar.gz, for example the sujet01_Lwhite.inflated.surf.gii. The image orientation also looks odd with [independent Matlab scripts](https://www.artefact.tk/software/matlab/gifti/), so perhaps this is an issue with the reference images rather than the Connectome Workbench. However, since the GIfTI format was developed by the Workbench team, it might be good to determine if these odd images should be removed from the reference, or if the GIfTI specification should be clarified to allow consistent performance across tools.

**Comment by glasserm** [comment]
I think the issue is likely with the header of the NIFTI file OR it is possible that the surface coordinates were not saved correctly.

**Comment by neurolabusc** [comment]
Thanks for the clarification. I am closing this issue, as the problem is with the GIfTI reference dataset, not Connectome Viewer. I have posted a [issue on the GIfTI NITRC forum](https://www.nitrc.org/forum/forum.php?thread_id=9893&forum_id=281).

**Comment by johnvelab** [comment]
The sample file is unusual in having dorsal coordinates less than ventral coordinates in the Z-dimension.  However, both the data and transformed spaces in the matrix are NIFTI_XFORM_UNKNOWN implying the surfaces are in no particular stereotaxic space.  While most surfaces are in a “Talairach-like Coordinate Space”, these sample files are valid, but uncommon.

John Harwell

On Jan 8, 2019, at 6:40 AM, Chris Rorden <notifications@github.com<mailto:notifications@github.com>> wrote:


When I attempt to load reference GIfTI images<https://www.nitrc.org/frs/?group_id=75> they appear upside down (flipped in the head-foot dimension). Viewing the GIfTI header with a text editor suggests it uses an identity matrix, so this would not be influenced by applying the matrix to the points. I am using wb_view 1.3.2 on MacOS. The images that look wrong are the Brainvisa GIFTI samples v1.3 included in the BV_GIFTI_1.3.tar.gz, for example the sujet01_Lwhite.inflated.surf.gii. The image orientation also looks odd with independent Matlab scripts<https://www.artefact.tk/software/matlab/gifti/>, so perhaps this is an issue with the reference images rather than the Connectome Workbench. However, since the GIfTI format was developed by the Workbench team, it might be good to determine if these odd images should be removed from the reference, or if the GIfTI specification should be clarified to allow consistent performance across tools.
