### ISSUE TITLE
Trouble opening nifti file

### ISSUE THREAD

**Issue by zf96** [Washington-University/workbench#32]
I'm having trouble with opening a nifti (.nii) file of fMRI activity downloaded from Neurosynth. I am trying to display the activity on an inflated brain but the only way I can actually view the activity from the nifti file is in the "Volume" mode which just shows it as a brain scan. Anyone know how to open a nifti file and display it on an inflated brain in Workbench?

**Comment by coalsont** [comment]
A standard nifti file is only a volume file (think 3D bitmap, just a big grid of cubes), and does not contain surface-based data, thus by design it is only viewable in Volume and All modes in wb_view.  To see its data on the surface, you need to decide which (anatomical) surfaces match the particular volume file you have, and then use wb_command -volume-to-surface-mapping (or other similar tools), which will find how the surface triangles/vertices intersect the voxels in the volume file, and use that information to find what the implied value at each surface vertex is.  Those values can then be displayed on non-anatomical surfaces, such as inflated surfaces.

In the HCP pipelines (and in our earlier work, and in freesurfer-based analysis...), we do this at the individual subject level, so as to avoid averaging voxel-based data across subjects, because volume-based registration generally doesn't align related cortex across subjects as well as surface-based registration.  volume-based averaging poses further challenges to generating accurate surface maps. 
 See our recent paper on these issues:

https://www.ncbi.nlm.nih.gov/pubmed/29925602

Incidentally, the github issues page is intended for reporting bugs in the software (crashes, etc).  For general help in using data, the hcp-users email list is generally a better place to ask questions (sign up at https://www.humanconnectome.org/contact-us , on the lower right).
