### ISSUE TITLE
Issue creating label file with a name not in -cifti-create-label list

### ISSUE THREAD

**Issue by anjaniragothaman** [Washington-University/workbench#33]
I'm trying to create a dlabel file with ROIs red nucleus, substantia nigra, subthalamic nucleus, Pallidum - internal and external and other freesurfer subcortical ROIs. I'm able to create the volume label file, but I'm not able to create the dlabel file with all the ROI labels. Only the ROIs with the names that match exactly with the list of structures mentioned in -cifti-create-labels are being created. How do I create a dlabel file with other structures included?

**Comment by coalsont** [comment]
While you can make arbitrary labels in the data of a cifti file, the allowed structures must be chosen from a fixed list.  Every voxel/vertex used must be assigned to a structure from that list (these define how the indices are ordered in the cifti file).  You can subdivide these structures as desired in a dlabel file by having multiple labels inside a structure.

To be clear, in -cifti-create-label, for your use case the <label-volume> should contain the red nucleus, etc labels, while the <structure-label-volume> should only contain labels like PALLIDUM_LEFT, etc from that list, and the two files should have overlap.  We plan to revise the list in the future, so if the ROIs you want are outside any of the given structures, please suggest any additional structures that should be in this list.  In the short term, you could make use of the "OTHER" structure name.

If you want to use the standard grayordinate space, consider using -cifti-create-dense-from-template with the -volume-all option, so that you don't have to generate the <structure-label-volume> file.
