### ISSUE TITLE
HCP workbench v1.5.0 wb_view segmentation fault

### ISSUE THREAD

**Issue by ShaoshiZ** [Washington-University/workbench#49]
Hi,

I am using CentOS7 and have installed workbench v.1.5.0. I receive a libGL error when I try to open wb_view
```
Info: Resources loaded:
   :/About   :/BalsaUploadDialog   :/Cursor   :/Fonts   :/general_resources.qrc   :/help_resources.qrc   :/HelpFiles   :/LayersPanel   :/OLD_help_resources.qrc   :/PaletteEditorDialog   :/PaletteSettings   :/qt-project.org   :/RecentFilesDialog   :/SceneFileDialog   :/SpecFileDialog   :/Splash   :/ToolBar   :/update_resources.sh

libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```
The user interface can still be loaded but it exits when I click 'Open Other...' and shows this error
```
bin_rh_linux64/wb_view: line 17: 38300 Segmentation fault      "$directory"/../exe_rh_linux64/wb_view "$@"
```

Any suggestions about how to fix this problem? Thank you.

Regards,
Shaoshi

**Comment by glasserm** [comment]
Is this on a physical display or via some kind of remote access?

**Comment by ShaoshiZ** [comment]
> Is this on a physical display or via some kind of remote access?

I am accessing it via VNC.

**Comment by glasserm** [comment]
You may need to install the virtualGL package and launch with vglrun wb_view ...

**Comment by ShaoshiZ** [comment]
> You may need to install the virtualGL package and launch with vglrun wb_view ...

Thanks for the suggestion. But is this specifically required by workbench v.1.5.0? I'm asking this because I can open workbench v.1.4.2 by directly running wb_view without virtualGL.

**Comment by johnvelab** [comment]
Does running “glxgears” work (may not be installed on your computer)?

Also, what is the output of “glxinfo”?

Try running “LIBGL_DEBUG=verbose  wb_view”.  What output does it produce?


John

From: "Shaoshi.Z" ***@***.***>
Reply-To: Washington-University/workbench ***@***.***>
Date: Thursday, April 22, 2021 at 4:46 AM
To: Washington-University/workbench ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Washington-University/workbench] HCP workbench v1.5.0 wb_view segmentation fault (#49)

* External Email - Caution *

You may need to install the virtualGL package and launch with vglrun wb_view ...

Thanks for the suggestion. But is this specifically required by workbench v.1.5.0? I'm asking this because I can open workbench v.1.4.2 by directly running wb_view without virtualGL.

**Comment by ShaoshiZ** [comment]
Thanks for the reply! 
* Yes, running `glxgears` works (It shows a 3D animation of 3 rotating gears). 
* Running `glxinfo` outputs a long list of information, I am not sure what information I should look out for?
* When I run `LIBGL_DEBUG=verbose  wb_view` under workbench v.1.5.0 folder, the GUI can pop up with some warnings
```
QGtkStyle was unable to detect the current GTK+ theme.
libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/shaoshi.z/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/shaoshi.z/.drirc: No such file or directory.
```
but the version shown in GUI is 1.1.1, not 1.5.0. Everything else seems to be working fine.

Shaoshi

**Comment by johnvelab** [comment]
You appear to have multiple versions of wb_view installed on your computer.

What is the command you use to run wb_view 1.5.0?

Try “LIBGL_DEBUG=verbose” followed by the command you use to run wb_view 1.5.0.

From: "Shaoshi.Z" ***@***.***>
Reply-To: Washington-University/workbench ***@***.***>
Date: Thursday, April 22, 2021 at 11:21 AM
To: Washington-University/workbench ***@***.***>
Cc: johnvelab ***@***.***>, Comment ***@***.***>
Subject: Re: [Washington-University/workbench] HCP workbench v1.5.0 wb_view segmentation fault (#49)

* External Email - Caution *

Thanks for the reply!

  *   Yes, running glxgears works (It shows a 3D animation of 3 rotating gears).
  *   Running glxinfo outputs a long list of information, I am not sure what information I should look out for?
  *   When I run LIBGL_DEBUG=verbose wb_view under workbench v.1.5.0 folder, the GUI can pop up with some warnings

QGtkStyle was unable to detect the current GTK+ theme.

libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so

libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so

libGL: Can't open configuration file /etc/drirc: No such file or directory.

libGL: Can't open configuration file /home/shaoshi.z/.drirc: No such file or directory.

libGL: Can't open configuration file /etc/drirc: No such file or directory.

libGL: Can't open configuration file /home/shaoshi.z/.drirc: No such file or directory.

but the version shown in GUI is 1.1.1, not 1.5.0. Everything else seems to be working fine.

Shaoshi

**Comment by ShaoshiZ** [comment]
Sorry, my bad. I forgot I've set the default workbench version to 1.1.1. Now I receive the following warnings and errors when I open workbench 1.5.0
```
Info: Resources loaded:
   :/About   :/BalsaUploadDialog   :/Cursor   :/Fonts   :/general_resources.qrc   :/help_resources.qrc   :/HelpFiles   :/LayersPanel   :/OLD_help_resources.qrc   :/PaletteEditorDialog   :/PaletteSettings   :/qt-project.org   :/RecentFilesDialog   :/SceneFileDialog   :/SpecFileDialog   :/Splash   :/ToolBar   :/update_resources.sh

libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL: dlopen /usr/lib64/dri/swrast_dri.so failed (/apps/HCP/workbench-1.5.0/bin_rh_linux64/../libs_rh_linux64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/lib64/libLLVM-7-rhel.so))
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
/apps/HCP/workbench-1.5.0//bin_rh_linux64/wb_view: line 17: 74193 Segmentation fault      "$directory"/../exe_rh_linux64/wb_view "$@"
```

It still has the same issue as before.

**Comment by johnvelab** [comment]
The message

(/apps/HCP/workbench-1.5.0/bin_rh_linux64/../libs_rh_linux64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/lib64/libLLVM-7-rhel.so))

indicates it might be a libstdc++ problem.  We include libstdc++ in our distribution and it might be incompatible with your operating system.  Go into the workbench distribution’s “libs_rh_linux64” directory and rename libstdc++.so.6 to save_libstdc++.so.6 so that wb_view will not try to load it.  After that, try running wb_view.  If wb_view still fails, send us the output and then rename the library back to its original name.

From: "Shaoshi.Z" ***@***.***>
Reply-To: Washington-University/workbench ***@***.***>
Date: Thursday, April 22, 2021 at 12:51 PM
To: Washington-University/workbench ***@***.***>
Cc: johnvelab ***@***.***>, Comment ***@***.***>
Subject: Re: [Washington-University/workbench] HCP workbench v1.5.0 wb_view segmentation fault (#49)

* External Email - Caution *

Sorry, my bad. I forgot I've set the default workbench version to 1.1.1. Now I receive the following warnings and errors when I open workbench 1.5.0

Info: Resources loaded:

   :/About   :/BalsaUploadDialog   :/Cursor   :/Fonts   :/general_resources.qrc   :/help_resources.qrc   :/HelpFiles   :/LayersPanel   :/OLD_help_resources.qrc   :/PaletteEditorDialog   :/PaletteSettings   :/qt-project.org   :/RecentFilesDialog   :/SceneFileDialog   :/SpecFileDialog   :/Splash   :/ToolBar   :/update_resources.sh



libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so

libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so

libGL: dlopen /usr/lib64/dri/swrast_dri.so failed (/apps/HCP/workbench-1.5.0/bin_rh_linux64/../libs_rh_linux64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/lib64/libLLVM-7-rhel.so))

libGL error: unable to load driver: swrast_dri.so

libGL error: failed to load driver: swrast

/apps/HCP/workbench-1.5.0//bin_rh_linux64/wb_view: line 17: 74193 Segmentation fault      "$directory"/../exe_rh_linux64/wb_view "$@"

It still has the same issue as before.

**Comment by ShaoshiZ** [comment]
Thanks for the suggestion. I think I have fixed the problem. I copied libstdc++.so.6.0.19 from `/usr/lib64` to `/workbench-1.5.0/libs_rh_linux64` and renamed it to libstdc++.so.6. Now everything is working.

BTW, I noticed that, at the top of the GUI, it actually shows 'Connectome Workbench 1.4.2' instead of '1.5.0'.

Shaoshi

**Comment by coalsont** [comment]
Thanks for mentioning the version, looks like the zip downloads on humanconnectome didn't get the right versions, there was a minor mishap that didn't get corrected properly - it is literally only one commit behind, the commit that changed the version number (and nothing else).

**Comment by coalsont** [comment]
The versions on humanconnectome should report the correct version now.
