### ISSUE TITLE
clang fails to compile workbench: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]

### ISSUE THREAD

**Issue by yurivict** [Washington-University/workbench#60]
```
/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:657:28: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]
        int extrema[6] = { myMap[0].m_ijk[0],
                           ^~~~~~~~~~~~~~~~~
/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:657:28: note: insert an explicit cast to silence this issue
        int extrema[6] = { myMap[0].m_ijk[0],
                           ^~~~~~~~~~~~~~~~~
                           static_cast<int>()
/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:658:13: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]
            myMap[0].m_ijk[0],
            ^~~~~~~~~~~~~~~~~
/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:658:13: note: insert an explicit cast to silence this issue
            myMap[0].m_ijk[0],
            ^~~~~~~~~~~~~~~~~
            static_cast<int>()
/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:659:13: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]
            myMap[0].m_ijk[1],
            ^~~~~~~~~~~~~~~~~
```

clang-13
FreeBSD 13.1

**Comment by johnvelab** [comment]
You can try this option when running CMake:


-DCMAKE_CXX_FLAGS="-Wno-error=c++11-narrowing”

OR

We have not used clang on Linux.  Can you use the GNU compiler instead of clang?  If the GNU compiler is used, narrowing should only be reported as a warning, not an error (see line 144 of src/Makefile).

John Harwell

From: ***@***.*** ***@***.***>
Date: Wednesday, July 6, 2022 at 12:50 PM
To: Washington-University/workbench ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Washington-University/workbench] clang fails to compile workbench: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing] (Issue #60)
* External Email - Caution *

/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:657:28: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]

        int extrema[6] = { myMap[0].m_ijk[0],

                           ^~~~~~~~~~~~~~~~~

/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:657:28: note: insert an explicit cast to silence this issue

        int extrema[6] = { myMap[0].m_ijk[0],

                           ^~~~~~~~~~~~~~~~~

                           static_cast<int>()

/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:658:13: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]

            myMap[0].m_ijk[0],

            ^~~~~~~~~~~~~~~~~

/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:658:13: note: insert an explicit cast to silence this issue

            myMap[0].m_ijk[0],

            ^~~~~~~~~~~~~~~~~

            static_cast<int>()

/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Algorithms/AlgorithmCiftiSeparate.cxx:659:13: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]

            myMap[0].m_ijk[1],

            ^~~~~~~~~~~~~~~~~

clang-13
FreeBSD 13.1

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2Fworkbench%2Fissues%2F60&data=05%7C01%7Cjharwell%40wustl.edu%7C0f246b715b0340cbb75f08da5f7800bc%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927266259293906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tnxmIFk41MCw1naneAaIV%2B%2Fq%2BWR7TYzB6WLV1XKpCIE%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALSGXBN7H267KRD7TSIJ3DVSXBN5ANCNFSM522SLDVQ&data=05%7C01%7Cjharwell%40wustl.edu%7C0f246b715b0340cbb75f08da5f7800bc%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927266259293906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5IGgF9NI9jjYR6KSJJR9tC1YqTCVeHTMly%2BscBbMg8s%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.
