### ISSUE TITLE
Doesn't print the message about QuaZip correctly

### ISSUE THREAD

**Issue by yurivict** [Washington-University/workbench#62]
This message lacks the library name:
```
    QuaZip:   Using QuaZip Library 
```
because the code looks like this:
```
SET(QuaZip-Qt5_RESULT "Using QuaZip Library ${QuaZip-Qt5_LIBRARIES}")
```

**Comment by johnvelab** [comment]
Where is this?  I do not see it in our CMakeLists.txt files.


SET(QuaZip-Qt5_RESULT "Using QuaZip Library ${QuaZip-Qt5_LIBRARIES}")

We do have this statement.  It tells us if QuaZip is from a system library or from quazip in our source code in the summary after CMake finishes.  It is not used when compiling/linking.


SET(QUAZIP_RESULT "Using QuaZip Library ${QUAZIP_LIBRARIES}")



From: ***@***.*** ***@***.***>
Date: Wednesday, July 6, 2022 at 1:20 PM
To: Washington-University/workbench ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Washington-University/workbench] Doesn't print a message about QuaZip correctly (Issue #62)
* External Email - Caution *

This message lacks the library name:

    QuaZip:   Using QuaZip Library

because the code looks like this:

SET(QuaZip-Qt5_RESULT "Using QuaZip Library ${QuaZip-Qt5_LIBRARIES}")

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2Fworkbench%2Fissues%2F62&data=05%7C01%7Cjharwell%40wustl.edu%7Cc29e62a2dc2c4d4f6f0608da5f7c224a%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927284001838748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=342uHAolNBOSFBrFr83aQiCAhbZ%2FUcuf6CmFhxTyzVI%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALSGXA4OVG3QF2NHFYS5C3VSXE4ZANCNFSM522U256Q&data=05%7C01%7Cjharwell%40wustl.edu%7Cc29e62a2dc2c4d4f6f0608da5f7c224a%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927284001838748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HxxXbbrLxvuKIdwM%2FZRcQ9a0kEULfnmI%2FfrZvo5GhwU%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.
