### ISSUE TITLE
error: use of undeclared identifier 'glGenBuffers'

### ISSUE THREAD

**Issue by yurivict** [Washington-University/workbench#64]
```
| /usr/bin/c++ -DHAVE_FREETYPE -DQT_CORE_LIB -DQT_NO_DEBUG -DWORKBENCH_HAVE_HELP_HTML -DWORKBENCH_USE_QT5_QOPENGL_WIDGET -D_STATICLIBBUILD -I/usr/local/include -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtGui -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Annotations -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Brain -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Charting -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Cifti -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/CZIlib/CZI -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/FilesBase -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Files -I/disk-samsung/freebsd-ports/biology/connec
work/workbench-1.5.0-430-g1e6d5c5c9/src/Brain/BrainOpenGLShape.cxx|177 col 9| error: use of undeclared identifier 'glGenBuffers'                                                              
||         glGenBuffers(1, &id);
||         ^
```

Did you forget to include ```GL/glext.h``` ?

**Comment by yurivict** [comment]
Same problem in src/Brain/BrainOpenGLShapeCone.cxx

**Comment by johnvelab** [comment]
glGenBuffers()  should be in GL/gl.h.  GLEW may be needed.

From: ***@***.*** ***@***.***>
Date: Wednesday, July 6, 2022 at 2:15 PM
To: Washington-University/workbench ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Washington-University/workbench] error: use of undeclared identifier 'glGenBuffers' (Issue #64)
* External Email - Caution *

| /usr/bin/c++ -DHAVE_FREETYPE -DQT_CORE_LIB -DQT_NO_DEBUG -DWORKBENCH_HAVE_HELP_HTML -DWORKBENCH_USE_QT5_QOPENGL_WIDGET -D_STATICLIBBUILD -I/usr/local/include -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtGui -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Annotations -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Brain -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Charting -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Cifti -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/CZIlib/CZI -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/FilesBase -I/disk-samsung/freebsd-ports/biology/connectome-workbench/work/workbench-1.5.0-430-g1e6d5c5c9/src/Files -I/disk-samsung/freebsd-ports/biology/connec

work/workbench-1.5.0-430-g1e6d5c5c9/src/Brain/BrainOpenGLShape.cxx|177 col 9| error: use of undeclared identifier 'glGenBuffers'

||         glGenBuffers(1, &id);

||         ^

Did you forget to include GL/glext.h ?

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2Fworkbench%2Fissues%2F64&data=05%7C01%7Cjharwell%40wustl.edu%7C959e1f27a8984264561508da5f83d4f0%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927317060158948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZXnt%2BXcEoyrCZAB1VA5f%2FBtnmRWrHcBjeRjwhpqL06c%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALSGXEOO4HXPGDF2JNBPH3VSXLLNANCNFSM522ZNWMA&data=05%7C01%7Cjharwell%40wustl.edu%7C959e1f27a8984264561508da5f83d4f0%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927317060158948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2v8dv1LR8W6G8cQRZ16A7Y1%2BLlx8CVdBeOrPOlQAFp0%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by yurivict** [comment]
Somehow ```#include <GL/gl.h>``` doesn't help.

**Comment by johnvelab** [comment]
That is where the function should be defined but you should not need to explicitly include the header.  The OpenGL headers are included by Graphics/CaretOpenGLInclude.h.

What is the output when cmake is run?  The output should show where OpenGL is found.



From: ***@***.*** ***@***.***>
Date: Wednesday, July 6, 2022 at 2:48 PM
To: Washington-University/workbench ***@***.***>
Cc: johnvelab ***@***.***>, Comment ***@***.***>
Subject: Re: [Washington-University/workbench] error: use of undeclared identifier 'glGenBuffers' (Issue #64)
* External Email - Caution *

Somehow #include <GL/gl.h> doesn't help.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2Fworkbench%2Fissues%2F64%23issuecomment-1176629017&data=05%7C01%7Cjharwell%40wustl.edu%7C4e2ec1d5fee64159f44b08da5f886d78%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927336804204762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LMT25zOSV0XNhBYfz2RoV%2FPiZ5x5BYJeAeUfFN%2F%2BgHs%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALSGXAYTTNOQA6V7NT72K3VSXPGZANCNFSM522ZNWMA&data=05%7C01%7Cjharwell%40wustl.edu%7C4e2ec1d5fee64159f44b08da5f886d78%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927336804204762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oeCkED2ZfXJm%2Fkfk4K4apGpig%2Bh5CdgjheF7TxRZq0A%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by yurivict** [comment]
```
===>  Configuring for connectome-workbench-1.5.0.430
===>  Performing out-of-source build
/bin/mkdir -p /disk-samsung/freebsd-ports/biology/connectome-workbench/work/.build
-- The C compiler identification is Clang 13.0.0
-- The CXX compiler identification is Clang 13.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_NO_COPY_DEPRECATED_FLAG
-- Performing Test HAVE_NO_COPY_DEPRECATED_FLAG - Success
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1o")  
-- Checking for module 'qwt5-qt5'
--   Found qwt5-qt5, version 5.2.3
-- Checking for module 'glm'
--   Found glm, version 0.9.8
CMake Warning (dev) at /usr/local/share/cmake/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/local/lib/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/local/lib/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/local/lib/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:341 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/local/lib/libOpenGL.so   
OpenGL Include Directory: /usr/local/include
OpenGL Libraries: /usr/local/lib/libGL.so;/usr/local/lib/libGLU.so
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.12") 
-- YURI QuaZip-Qt5 found
-- Found Freetype: /usr/local/lib/libfreetype.so (found version "2.11.1") 
-- Checking for module 'ftgl'
--   Found ftgl, version 2.4.0
************* SUMMARY FROM RUNNING CMake ********************
TOOLS:
    CMake Build Type:     Release
    CMake Version:        3.23.0
    CXX Compiler          Clang
    CXX Compiler Version: 13.0.0
    CXX Compiler Flags:   -fopenmp=libomp -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include/QuaZip-Qt5-1.3/quazip
    CXX Compiler Path:    /usr/bin/c++
    QMake Program:        QMAKE_PROGRAM-NOTFOUND
WORKBENCH VARIABLES:
    WORKBENCH_APPLE_WB_COMMAND_BUNDLE_FLAG=TRUE
        On Apple Only: 
           If TRUE, build wb_command as a MacOS Bundle (wb_command.app).
           If FALSE, build wb_command as a normal UNIX executable.
    WORKBENCH_INCLUDE_HELP_HTML_RESOURCES=TRUE
        If TRUE, help (html) pages in src/Resources/Help are available in wb_view
    WORKBENCH_MESA_DIR=
        Directory containing Mesa's 'include' and 'lib' 
        directories.  Mesa is optional and used by 
        wb_command's -show-scene operation.
    WORKBENCH_OPENMP_COMPILER_FLAGS=
        OpenMP compiler flags for when FindOpenMP does not work
    WORKBENCH_OPENMP_INCLUDE_DIR=
        OpenMP include directory for when FindOpenMP does not work
    WORKBENCH_OPENMP_LIBRARY=
        OpenMP library path (path and lib) for when FindOpenMP does not work
    WORKBENCH_QT5_DISABLE_DEPRECATED=FALSE
        If TRUE, use of Qt 5 deprecated functionality will cause compiler to fail
    WORKBENCH_USE_CMAKE_AUTOMOC=FALSE
        If TRUE, use CMAKE_AUTOMOC command for generating 'moc' files
    WORKBENCH_USE_QT5=ON
        No help, variable specified on the command line.
    WORKBENCH_USE_QT5_QOPENGL_WIDGET=ON
        No help, variable specified on the command line.
    WORKBENCH_USE_QT6=OFF
        No help, variable specified on the command line.
PACKAGES:
    FTGL:     Using FTGL Library ftgl
    FreeType: 2.11.1 /usr/local/lib/libfreetype.so
    GLEW:     No
    GLMath:   Using OpenGL Math directory /usr/local/include
    OpenGL:   /usr/local/lib/libGL.so/usr/local/lib/libGLU.so
    OpenMP:   Yes
    OpenSSL:  1.1.1o   /usr/lib/libssl.so/usr/lib/libcrypto.so
    OSMESA:   Not found
    Qt:       5.15.2
    QuaZip:   Using QuaZip Library 
    Qwt:      Using Qwt Library qwt5-qt5Qt5PrintSupportQt5SvgQt5WidgetsQt5GuiQt5Core
    SIMD:     Search for SIMD disabled for compiler on this system.
    ZLIB:     1.2.12
************* END SUMMARY FROM RUNNING CMake *****************
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS_DEBUG
    CMAKE_C_FLAGS_DEBUG
    CMAKE_MODULE_LINKER_FLAGS
    CMAKE_SHARED_LINKER_FLAGS
    CMAKE_VERBOSE_MAKEFILE
    THREADS_HAVE_PTHREAD_ARG


-- Build files have been written to: /disk-samsung/freebsd-ports/biology/connectome-workbench/work/.build
```

**Comment by yurivict** [comment]
All packages are installed into /usr/local.

**Comment by yurivict** [comment]
Somehow the build fails to find glGenBuffers.

**Comment by johnvelab** [comment]
Is it only glGenBuffers() that is missing or is it reporting other “gl” functions as missing?  glGenBuffers() was added in OpenGL 2.0 (mid 1990s) so I doubt your version of OpenGL is that old.

You can try defining GL_GLEXT_PROTOTYPES. In src/Graphics/CaretOpenGLInclude.h, add “#define GL_GLEXT_PROTOTYPES” above “#include <GL/gl.h>” (look for •======= ADD THIS).


#ifdef CARET_OS_MACOSX
    #include <OpenGL/gl.h>
    #include <OpenGL/glu.h>
#else
    #ifndef HAVE_GLEW
        #ifdef CARET_OS_LINUX
            /*
             * On linux, adds support for newer OpenGL
             * as described at https://www.khronos.org/registry/OpenGL/ABI/
             */
            #define GL_GLEXT_PROTOTYPES
        #endif
    #endif

    #define GL_GLEXT_PROTOTYPES          •======= ADD THIS
    #include <GL/gl.h>
    #include <GL/glu.h>
#endif



Lastly, you may need to load your systems “gl.h” (maybe /usr/local/include/GL/gl.h) into an editor and try to find the “#ifdef” that prevents declarations of the OpenGL function prototypes.


From: ***@***.*** ***@***.***>
Date: Wednesday, July 6, 2022 at 3:49 PM
To: Washington-University/workbench ***@***.***>
Cc: johnvelab ***@***.***>, Comment ***@***.***>
Subject: Re: [Washington-University/workbench] error: use of undeclared identifier 'glGenBuffers' (Issue #64)
* External Email - Caution *

Somehow the build fails to find glGenBuffers.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2Fworkbench%2Fissues%2F64%23issuecomment-1176721919&data=05%7C01%7Cjharwell%40wustl.edu%7C39e8c012564648f7ac4308da5f910543%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927373708910293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e02MUIK5K8yOhdeCtGpDQ5kt%2FqhO%2BFhlkuq334x0a9g%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALSGXGBNWZYPVA4VWVYHZLVSXWNPANCNFSM522ZNWMA&data=05%7C01%7Cjharwell%40wustl.edu%7C39e8c012564648f7ac4308da5f910543%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927373708910293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x0zE63hqSjevcLG2FK%2BmlHwlEGH%2F5jMzPD4n5fmOJ%2B0%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by djgerah** [comment]
use #include <GLES/gl.h>

**Comment by johnvelab** [comment]
GLES/gl.h are the headers for OpenGL ES 1.1.  (ES = Embedded Systems).  We use desktop OpenGL with headers in "GL".

https://registry.khronos.org/OpenGL/index_es.php
