### ISSUE TITLE
Fails to find Qt and Qwt libraries

### ISSUE THREAD

**Issue by yurivict** [Washington-University/workbench#68]
```
ld: error: unable to find library -lqwt6
ld: error: unable to find library -lQt5Concurrent
ld: error: unable to find library -lQt5PrintSupport
ld: error: unable to find library -lQt5Svg
ld: error: unable to find library -lQt5OpenGL
ld: error: unable to find library -lQt5Widgets
ld: error: unable to find library -lQt5Gui
ld: error: unable to find library -lQt5Core
```

**Comment by yurivict** [comment]
And the same problem with quazip1-qt5

**Comment by johnvelab** [comment]
In the build directory of Workbench, edit CMakeCache.txt, set CMAKE_VERBOSE_MAKEFILE to TRUE, rerun cmake, and make.  It should show the full link command with a “-L” to the directory containing the Qt libraries.   Also look for the Qwt6 path.

Run “which qmake” and it will show the path to the Qt bin directory.  Up one level is “lib” and it should contain the Qt libraries.  Does it contain the missing libraries?


From: ***@***.*** ***@***.***>
Date: Wednesday, July 6, 2022 at 10:12 PM
To: Washington-University/workbench ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Washington-University/workbench] Fails to find Qt and Qwt libraries (Issue #68)
* External Email - Caution *

ld: error: unable to find library -lqwt6

ld: error: unable to find library -lQt5Concurrent

ld: error: unable to find library -lQt5PrintSupport

ld: error: unable to find library -lQt5Svg

ld: error: unable to find library -lQt5OpenGL

ld: error: unable to find library -lQt5Widgets

ld: error: unable to find library -lQt5Gui

ld: error: unable to find library -lQt5Core

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2Fworkbench%2Fissues%2F68&data=05%7C01%7Cjharwell%40wustl.edu%7C767aee9153f14ea54ee108da5fc67793%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927603263365948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6DrYpl3jHI8rtCkuX2cF0poy3hTAGf9bPHSeFqTLuYM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALSGXCHXL5KNODPCG6ALNDVSZDIDANCNFSM523Z5C7Q&data=05%7C01%7Cjharwell%40wustl.edu%7C767aee9153f14ea54ee108da5fc67793%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637927603263365948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N5R8miQOq2FvpPD%2BpELDmasVggu2VUNYLmw2CsQxVsE%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by yurivict** [comment]
> Does it contain the missing libraries?

No, it doesn't.
I had to add these extra link flags to work around the problem:

```
LDFLAGS+=      `pkg-config --libs Qt5Concurrent Qt5PrintSupport Qt5Svg Qt5OpenGL Qt5Widgets Qt5Gui Qt5Core Qt5Qwt6`
```

You probably forgot to add Qt target to some of the binaries you build.

**Comment by yurivict** [comment]
```
FAILED: Desktop/wb_view 
: && /usr/bin/c++ -fopenmp=libomp -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include/QuaZip-Qt5-1.3/quazip -DGL_GLEXT_PROTOTYPES -isystem /usr/local/include -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include/QuaZip-Qt5-1.3/quazip -DGL_GLEXT_PROTOTYPES -isystem /usr/local/include -lexecinfo -lquazip1-qt5 -fstack-protector-strong -L/usr/local/lib Desktop/CMakeFiles/wb_view.dir/desktop.cxx.o Desktop/CMakeFiles/wb_view.dir/qrc_general_resources.cpp.o Desktop/CMakeFiles/wb_view.dir/qrc_gui_resources.cpp.o Desktop/CMakeFiles/wb_view.dir/qrc_help_resources.cpp.o -o Desktop/wb_view  -Wl,-rpath,/usr/local/lib:/usr/local/lib/qt5:  GuiQt/libGuiQt.a  Commands/libCommands.a  Operations/libOperations.a  Algorithms/libAlgorithms.a  OperationsBase/libOperationsBase.a  -lqwt6  -lQt5Concurrent  -lQt5PrintSupport  -lQt5Svg  -lQt5OpenGL  -lQt5Widgets  -lQt5Gui  -lQt5Core  OSMesaDummy/libOSMesaDummy.a  Brain/libBrain.a  Files/libFiles.a  Graphics/libGraphics.a  -lftgl  Annotations/libAnnotations.a  Charting/libCharting.a  Palette/libPalette.a  Cifti/libCifti.a  Gifti/libGifti.a  Nifti/libNifti.a  QxtCore/libQxtCore.a  FilesBase/libFilesBase.a  Scenes/libScenes.a  Xml/libXml.a  CZIlib/CZICmd/libCZICmd.a  CZIlib/CZI/libCZI.a  CZIlib/CZIJxrDecode/libCZIJxrDecode.a  Common/libCommon.a  /usr/local/lib/libGLEW.so  /usr/local/lib/libfreetype.so  /usr/local/lib/qt5/libQt5Concurrent.so.5.15.2  /usr/local/lib/qt5/libQt5Network.so.5.15.2  /usr/local/lib/qt5/libQt5PrintSupport.so.5.15.2  /usr/local/lib/qt5/libQt5Test.so.5.15.2  /usr/local/lib/qt5/libQt5Widgets.so.5.15.2  /usr/local/lib/qt5/libQt5Xml.so.5.15.2  -lz  /usr/local/lib/libGL.so  /usr/local/lib/libGLU.so  -lgobject-2.0  /usr/local/lib/qt5/libQt5Gui.so.5.15.2  /usr/local/lib/qt5/libQt5Core.so.5.15.2  -Wl,-rpath-link,/usr/local/lib && :
ld: error: unable to find library -lqwt6
ld: error: unable to find library -lQt5Concurrent
ld: error: unable to find library -lQt5PrintSupport
ld: error: unable to find library -lQt5Svg
ld: error: unable to find library -lQt5OpenGL
ld: error: unable to find library -lQt5Widgets
ld: error: unable to find library -lQt5Gui
ld: error: unable to find library -lQt5Core
```

**Comment by johnvelab** [comment]
“ld: error: unable to find library -lQt5Concurrent” indicates that “-L <path-to-qt-libraries>” is missing or incorrect and needs to be prior to any of the “-lQt5<library-name>”.

In addition, all of the Qt libraries are specified two times in the link command.  One of the groups need to be removed.  For example, the command contains both:

  -lQt5Concurrent

and

/usr/local/lib/qt5/libQt5Concurrent.so.5.15.2




From: ***@***.*** ***@***.***>
Date: Thursday, July 7, 2022 at 1:08 PM
To: Washington-University/workbench ***@***.***>
Cc: johnvelab ***@***.***>, Comment ***@***.***>
Subject: Re: [Washington-University/workbench] Fails to find Qt and Qwt libraries (Issue #68)
* External Email - Caution *

FAILED: Desktop/wb_view

: && /usr/bin/c++ -fopenmp=libomp -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include/QuaZip-Qt5-1.3/quazip -DGL_GLEXT_PROTOTYPES -isystem /usr/local/include -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include/QuaZip-Qt5-1.3/quazip -DGL_GLEXT_PROTOTYPES -isystem /usr/local/include -lexecinfo -lquazip1-qt5 -fstack-protector-strong -L/usr/local/lib Desktop/CMakeFiles/wb_view.dir/desktop.cxx.o Desktop/CMakeFiles/wb_view.dir/qrc_general_resources.cpp.o Desktop/CMakeFiles/wb_view.dir/qrc_gui_resources.cpp.o Desktop/CMakeFiles/wb_view.dir/qrc_help_resources.cpp.o -o Desktop/wb_view  -Wl,-rpath,/usr/local/lib:/usr/local/lib/qt5:  GuiQt/libGuiQt.a  Commands/libCommands.a  Operations/libOperations.a  Algorithms/libAlgorithms.a  OperationsBase/libOperationsBase.a  -lqwt6  -lQt5Concurrent  -lQt5PrintSupport  -lQt5Svg  -lQt5OpenGL  -lQt5Widgets  -lQt5Gui  -lQt5Core  OSMesaDummy/libOSMesaDummy.a  Brain/libBrain.a  Files/libFiles.a  Graphics/libGraphics.a  -lftgl  Annotations/libAnnotations.a  Charting/libCharting.a  Palette/libPalette.a  Cifti/libCifti.a  Gifti/libGifti.a  Nifti/libNifti.a  QxtCore/libQxtCore.a  FilesBase/libFilesBase.a  Scenes/libScenes.a  Xml/libXml.a  CZIlib/CZICmd/libCZICmd.a  CZIlib/CZI/libCZI.a  CZIlib/CZIJxrDecode/libCZIJxrDecode.a  Common/libCommon.a  /usr/local/lib/libGLEW.so  /usr/local/lib/libfreetype.so  /usr/local/lib/qt5/libQt5Concurrent.so.5.15.2  /usr/local/lib/qt5/libQt5Network.so.5.15.2  /usr/local/lib/qt5/libQt5PrintSupport.so.5.15.2  /usr/local/lib/qt5/libQt5Test.so.5.15.2  /usr/local/lib/qt5/libQt5Widgets.so.5.15.2  /usr/local/lib/qt5/libQt5Xml.so.5.15.2  -lz  /usr/local/lib/libGL.so  /usr/local/lib/libGLU.so  -lgobject-2.0  /usr/local/lib/qt5/libQt5Gui.so.5.15.2  /usr/local/lib/qt5/libQt5Core.so.5.15.2  -Wl,-rpath-link,/usr/local/lib && :

ld: error: unable to find library -lqwt6

ld: error: unable to find library -lQt5Concurrent

ld: error: unable to find library -lQt5PrintSupport

ld: error: unable to find library -lQt5Svg

ld: error: unable to find library -lQt5OpenGL

ld: error: unable to find library -lQt5Widgets

ld: error: unable to find library -lQt5Gui

ld: error: unable to find library -lQt5Core

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2Fworkbench%2Fissues%2F68%23issuecomment-1178020433&data=05%7C01%7Cjharwell%40wustl.edu%7C3df43f9fa0eb40d8f44008da6043a76d%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637928140972063670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xNSqb6FuZPuJtsEfPpRo4gLdbfxmII%2BoH0FXget3izc%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALSGXA3NNG3HM7BOFY7JGDVS4MITANCNFSM523Z5C7Q&data=05%7C01%7Cjharwell%40wustl.edu%7C3df43f9fa0eb40d8f44008da6043a76d%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637928140972063670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C%2FUr6lfxHCeqqwXLLhKaWGWS8Zyis7jBR5e7Levvlbo%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.
